# Generated by Django 6.0.3 on 2026-03-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedbacks/')),
                ('name', models.JSONField(default=dict)),
                ('role', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.JSONField(default=dict)),
                ('shortDescription', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botToken', models.CharField(default='8632538695:AAGrBNDrqUPxpu5N7pzKK8Zpemd0M8kYlS4', max_length=255)),
                ('chatId', models.CharField(default='5046205739', max_length=255)),
                ('adminLogin', models.CharField(default='admin', max_length=100)),
                ('adminPassword', models.CharField(default='admin777', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('name', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('title', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.achievementcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('name', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('teacher', models.JSONField(default=dict)),
                ('time', models.JSONField(default=dict)),
                ('level', models.JSONField(default=dict)),
                ('room', models.JSONField(default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.coursecategory')),
            ],
        ),
    ]
