# Generated by Django 6.0.3 on 2026-03-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_options_remove_achievement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='en',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='achievementcategory',
            name='en',
        ),
        migrations.RemoveField(
            model_name='achievementcategory',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='achievementcategory',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='en',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='en',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='uz',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='ru',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='uz',
        ),
        migrations.AddField(
            model_name='achievement',
            name='desc_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='desc_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='desc_uz',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='achievementcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='achievementcategory',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='achievementcategory',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_uz',
            field=models.TextField(default='', verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Darajasi (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Darajasi (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Darajasi (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Xona (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Xona (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Xona (UZ)'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="O'qituvchi (EN)"),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="O'qituvchi (RU)"),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_uz',
            field=models.CharField(default='', max_length=255, verbose_name="O'qituvchi (UZ)"),
        ),
        migrations.AddField(
            model_name='course',
            name='time_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Vaqti (EN)'),
        ),
        migrations.AddField(
            model_name='course',
            name='time_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Vaqti (RU)'),
        ),
        migrations.AddField(
            model_name='course',
            name='time_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Vaqti (UZ)'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fikr (EN)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fikr (RU)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_uz',
            field=models.TextField(default='', verbose_name='Fikr (UZ)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ism (EN)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ism (RU)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Ism (UZ)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='role_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Roli (EN)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='role_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Roli (RU)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='role_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Roli (UZ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name="To'liq tavsif (EN)"),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name="To'liq tavsif (RU)"),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_uz',
            field=models.TextField(default='', verbose_name="To'liq tavsif (UZ)"),
        ),
        migrations.AddField(
            model_name='news',
            name='short_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qisqa tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_uz',
            field=models.TextField(default='', verbose_name='Qisqa tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ism (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ism (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Ism (UZ)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='pos_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Lavozim (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='pos_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Lavozim (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='pos_uz',
            field=models.CharField(default='', max_length=255, verbose_name='Lavozim (UZ)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='typeMap',
            field=models.CharField(choices=[('portrait', 'Tik'), ('landscape', 'Yotiq')], default='portrait', max_length=20),
        ),
    ]
