# Generated by Django 6.0.3 on 2026-03-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_achievement_en_remove_achievement_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Asosiy rasm (Preview)'),
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video (YouTube)')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/media/', verbose_name='Rasm yuklash')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube havola (URL)')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.news')),
            ],
        ),
    ]
