# Generated by Django 6.0.3 on 2026-03-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_image_newsmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_processed', models.BooleanField(default=False, verbose_name="Ko'rib chiqildi")),
            ],
            options={
                'verbose_name': "Bog'lanish arizasi",
                'verbose_name_plural': "Bog'lanish arizalari",
            },
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Yutuq', 'verbose_name_plural': 'Yutuqlar'},
        ),
        migrations.AlterModelOptions(
            name='achievementcategory',
            options={'verbose_name': 'Yutuq kategoriyasi', 'verbose_name_plural': 'Yutuq kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Kurs kategoriyasi', 'verbose_name_plural': 'Kurs kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Fikr-mulohaza', 'verbose_name_plural': 'Fikr-mulohazalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Tizim sozlamasi', 'verbose_name_plural': 'Tizim sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': "Jamoa a'zolari"},
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='adminLogin',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='adminPassword',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='instagramLink',
            field=models.URLField(default='https://instagram.com/10dimi', verbose_name='Instagram sahifa'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phoneNumber',
            field=models.CharField(default='+998 (90) 123 45 67', max_length=50, verbose_name="Bog'lanish uchun telefon"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='telegramLink',
            field=models.URLField(default='https://t.me/10dimi', verbose_name='Telegram kanal'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='youtubeLink',
            field=models.URLField(default='https://youtube.com/10dimi', verbose_name='YouTube kanal'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='botToken',
            field=models.CharField(default='8632538695:AAGrBNDrqUPxpu5N7pzKK8Zpemd0M8kYlS4', max_length=255, verbose_name='Telegram Bot Token'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='chatId',
            field=models.CharField(default='5046205739', max_length=255, verbose_name='Telegram Chat ID (vergul bilan bir nechta)'),
        ),
    ]
